// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_CONNECTION_STRING'] = 'DefaultEndpointsProtocol=https;AccountName=xiaonlistage;AccountKey=null;EndpointSuffix=core.windows.net';
  process.env['AZURE_STORAGE_CONNECTION_STRING_BLOB_ACCOUNT_LRS'] = 'DefaultEndpointsProtocol=https;AccountName=xiaonlistageblob2;AccountKey=null;EndpointSuffix=core.windows.net';
  process.env['AZURE_STORAGE_CONNECTION_STRING_PREMIUM_ACCOUNT'] = 'DefaultEndpointsProtocol=https;AccountName=xiaonliprepp;AccountKey=null;EndpointSuffix=rr1xio.xstore-test.windows-int.net';
}

exports.scopes = [[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '25f39c5a-001c-0002-2490-dfcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:09 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '25f39c5a-001c-0002-2490-dfcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:09 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata0?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:10 GMT',
  etag: '"0x8D4ADA81086A8B7"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c7451cce-001c-0007-0690-df9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:10 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata0?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:10 GMT',
  etag: '"0x8D4ADA81086A8B7"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c7451cce-001c-0007-0690-df9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:10 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata0/archive-blob-testdata1')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:12 GMT',
  etag: '"0x8D4ADA81137C2CA"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '7d5ceb8d-001c-0006-1d90-df7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:10 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata0/archive-blob-testdata1')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:12 GMT',
  etag: '"0x8D4ADA81137C2CA"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '7d5ceb8d-001c-0006-1d90-df7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:10 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata0/archive-blob-testdata1')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:21:12 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA81137C2CA"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'p10',
  'x-ms-access-tier-inferred': 'true',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '26d7fdb7-001c-000a-1590-dfa714000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata0/archive-blob-testdata1')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:21:12 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA81137C2CA"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'p10',
  'x-ms-access-tier-inferred': 'true',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '26d7fdb7-001c-000a-1590-dfa714000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:10 GMT',
  etag: '"0x8D4ADA81086A8B7"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': 'e4e9c810-001c-000c-0e90-dfc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:13 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:10 GMT',
  etag: '"0x8D4ADA81086A8B7"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': 'e4e9c810-001c-000c-0e90-dfc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:13 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata0?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '45b4bb93-001c-0012-5290-df1f25000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:14 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata0?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '45b4bb93-001c-0012-5290-df1f25000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:14 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b3948aae-001c-0000-7e90-df1500000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:15 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b3948aae-001c-0000-7e90-df1500000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:15 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:16 GMT',
  etag: '"0x8D4ADA813F6D742"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b77fbabd-001c-0013-4e90-dff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:16 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:16 GMT',
  etag: '"0x8D4ADA813F6D742"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b77fbabd-001c-0013-4e90-dff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:16 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:17 GMT',
  etag: '"0x8D4ADA814A7A71A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'e7dcea97-001c-000e-6e90-df13e3000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:17 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:17 GMT',
  etag: '"0x8D4ADA814A7A71A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'e7dcea97-001c-000e-6e90-df13e3000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:17 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(200, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ce17cd1f-001c-0003-3290-df2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:18 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(200, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ce17cd1f-001c-0003-3290-df2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:18 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:21:17 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA814A7A71A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P4',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '6ef2815a-001c-0008-6c90-df7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:19 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:21:17 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA814A7A71A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P4',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '6ef2815a-001c-0008-6c90-df7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:19 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .get('/archive-cont-testdata2?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<EnumerationResults ServiceEndpoint=\"https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443/\" ContainerName=\"archive-cont-testdata2\"><Blobs><Blob><Name>archive-blob-testdata3</Name><Properties><Last-Modified>Wed, 07 Jun 2017 13:21:17 GMT</Last-Modified><Etag>0x8D4ADA814A7A71A</Etag><Content-Length>0</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding/><Content-Language/><Content-MD5/><Cache-Control/><Content-Disposition/><x-ms-blob-sequence-number>0</x-ms-blob-sequence-number><BlobType>PageBlob</BlobType><AccessTier>P4</AccessTier><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker/></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c5dfe66e-001c-0005-2690-df4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .get('/archive-cont-testdata2?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<EnumerationResults ServiceEndpoint=\"https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443/\" ContainerName=\"archive-cont-testdata2\"><Blobs><Blob><Name>archive-blob-testdata3</Name><Properties><Last-Modified>Wed, 07 Jun 2017 13:21:17 GMT</Last-Modified><Etag>0x8D4ADA814A7A71A</Etag><Content-Length>0</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding/><Content-Language/><Content-MD5/><Cache-Control/><Content-Disposition/><x-ms-blob-sequence-number>0</x-ms-blob-sequence-number><BlobType>PageBlob</BlobType><AccessTier>P4</AccessTier><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker/></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c5dfe66e-001c-0005-2690-df4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(200, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '897ec015-001c-0001-1090-dff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:21 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(200, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '897ec015-001c-0001-1090-dff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:21 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:21:17 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA814A7A71A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P6',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '3288da30-001c-0011-1f90-df28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:21:17 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA814A7A71A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P6',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '3288da30-001c-0011-1f90-df28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>CannotChangeToLowerTier</Code><Message>A higher blob tier has already been explicitly set.\nRequestId:484a0d09-001c-000b-3290-df4a69000000\nTime:2017-06-07T13:21:23.4988527Z</Message></Error>", { 'content-length': '244',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '484a0d09-001c-000b-3290-df4a69000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>CannotChangeToLowerTier</Code><Message>A higher blob tier has already been explicitly set.\nRequestId:484a0d09-001c-000b-3290-df4a69000000\nTime:2017-06-07T13:21:23.4988527Z</Message></Error>", { 'content-length': '244',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '484a0d09-001c-000b-3290-df4a69000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:21:17 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA814A7A71A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P6',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': 'c72d0f05-001c-000d-7690-df2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:21:17 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA814A7A71A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P6',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': 'c72d0f05-001c-000d-7690-df2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:16 GMT',
  etag: '"0x8D4ADA813F6D742"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '25f39c5d-001c-0002-2790-dfcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:25 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:16 GMT',
  etag: '"0x8D4ADA813F6D742"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '25f39c5d-001c-0002-2790-dfcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:25 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata2?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd580ef41-001c-000f-7c90-dffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:26 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata2?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd580ef41-001c-000f-7c90-dffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:26 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7d5ceb90-001c-0006-2090-df7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7d5ceb90-001c-0006-2090-df7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata4?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:27 GMT',
  etag: '"0x8D4ADA81A9E7519"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e4e9c813-001c-000c-1190-dfc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:27 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata4?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:27 GMT',
  etag: '"0x8D4ADA81A9E7519"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e4e9c813-001c-000c-1190-dfc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:27 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata4/archive-blob-testdata5')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:29 GMT',
  etag: '"0x8D4ADA81B80692A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'b77fbabf-001c-0013-5090-dff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:29 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata4/archive-blob-testdata5')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:29 GMT',
  etag: '"0x8D4ADA81B80692A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'b77fbabf-001c-0013-5090-dff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:29 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata4/archive-blob-testdata5temp')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:30 GMT',
  etag: '"0x8D4ADA81C110C6B"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '6ef2815c-001c-0008-6e90-df7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:29 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata4/archive-blob-testdata5temp')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:30 GMT',
  etag: '"0x8D4ADA81C110C6B"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '6ef2815c-001c-0008-6e90-df7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:29 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata4/archive-blob-testdata5temp')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:21:30 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA81C110C6B"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P10',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': 'c5dfe670-001c-0005-2890-df4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata4/archive-blob-testdata5temp')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:21:30 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA81C110C6B"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P10',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': 'c5dfe670-001c-0005-2890-df4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:27 GMT',
  etag: '"0x8D4ADA81A9E7519"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '897ec018-001c-0001-1390-dff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:27 GMT',
  etag: '"0x8D4ADA81A9E7519"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '897ec018-001c-0001-1390-dff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata4?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3288da33-001c-0011-2290-df28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:32 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata4?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3288da33-001c-0011-2290-df28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:32 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '484a0d0c-001c-000b-3590-df4a69000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '484a0d0c-001c-000b-3590-df4a69000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata6?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:34 GMT',
  etag: '"0x8D4ADA81E9E9E57"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c72d0f08-001c-000d-7990-df2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:33 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata6?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:34 GMT',
  etag: '"0x8D4ADA81E9E9E57"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c72d0f08-001c-000d-7990-df2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:33 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:36 GMT',
  etag: '"0x8D4ADA81F7F90D3"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '25f39c65-001c-0002-2990-dfcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:35 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:36 GMT',
  etag: '"0x8D4ADA81F7F90D3"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '25f39c65-001c-0002-2990-dfcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:35 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7temp')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>BlobTierInadequateForContentLength</Code><Message>Specified blob tier size limit cannot be less than content length.\nRequestId:c7451cd1-001c-0007-0990-df9671000000\nTime:2017-06-07T13:21:36.8350797Z</Message></Error>", { 'content-length': '270',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c7451cd1-001c-0007-0990-df9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7temp')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>BlobTierInadequateForContentLength</Code><Message>Specified blob tier size limit cannot be less than content length.\nRequestId:c7451cd1-001c-0007-0990-df9671000000\nTime:2017-06-07T13:21:36.8350797Z</Message></Error>", { 'content-length': '270',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c7451cd1-001c-0007-0990-df9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:34 GMT',
  etag: '"0x8D4ADA81E9E9E57"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '26846594-001c-0014-4f90-df7129000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:37 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:34 GMT',
  etag: '"0x8D4ADA81E9E9E57"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '26846594-001c-0014-4f90-df7129000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:37 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata6?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e4e9c815-001c-000c-1390-dfc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:38 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata6?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e4e9c815-001c-000c-1390-dfc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:38 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '45b4bb97-001c-0012-5690-df1f25000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '45b4bb97-001c-0012-5690-df1f25000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata8?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:40 GMT',
  etag: '"0x8D4ADA821F9BA92"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b3948ab2-001c-0000-0290-df1500000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:40 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata8?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:40 GMT',
  etag: '"0x8D4ADA821F9BA92"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b3948ab2-001c-0000-0290-df1500000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:40 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:41 GMT',
  etag: '"0x8D4ADA822ECB55D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'b77fbac1-001c-0013-5291-dff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:41 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:41 GMT',
  etag: '"0x8D4ADA822ECB55D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'b77fbac1-001c-0013-5291-dff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:41 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9temp')
  .reply(500, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>InternalError</Code><Message>Server encountered an internal error. Please try again after some time.\nRequestId:ce17cd28-001c-0003-3591-df2286000000\nTime:2017-06-07T13:21:42.2934115Z</Message></Error>", { 'content-length': '254',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ce17cd28-001c-0003-3591-df2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9temp')
  .reply(500, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>InternalError</Code><Message>Server encountered an internal error. Please try again after some time.\nRequestId:ce17cd28-001c-0003-3591-df2286000000\nTime:2017-06-07T13:21:42.2934115Z</Message></Error>", { 'content-length': '254',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ce17cd28-001c-0003-3591-df2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:40 GMT',
  etag: '"0x8D4ADA821F9BA92"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '6ef2815e-001c-0008-7091-df7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:40 GMT',
  etag: '"0x8D4ADA821F9BA92"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '6ef2815e-001c-0008-7091-df7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata8?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c5dfe673-001c-0005-2b91-df4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:44 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata8?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c5dfe673-001c-0005-2b91-df4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:44 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '290d4199-001c-0004-2e91-dfa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '290d4199-001c-0004-2e91-dfa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:46 GMT',
  etag: '"0x8D4ADA825BAFB71"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '897ec01a-001c-0001-1591-dff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:46 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:46 GMT',
  etag: '"0x8D4ADA825BAFB71"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '897ec01a-001c-0001-1591-dff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:46 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:47 GMT',
  etag: '"0x8D4ADA826571A18"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '3288da35-001c-0011-2491-df28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:47 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:47 GMT',
  etag: '"0x8D4ADA826571A18"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '3288da35-001c-0011-2491-df28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:47 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:48 GMT',
  etag: '"0x8D4ADA826E9E0BE"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '25f39c68-001c-0002-2b91-dfcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:48 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:48 GMT',
  etag: '"0x8D4ADA826E9E0BE"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '25f39c68-001c-0002-2b91-dfcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:48 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata10/archive-blob-testdata11?comp=page', '*')
  .reply(201, "", { 'content-md5': 'VJXsRKPJgaTKv8EXnmtrQg==',
  'last-modified': 'Wed, 07 Jun 2017 13:21:52 GMT',
  etag: '"0x8D4ADA82907ECEB"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '45b4bb9f-001c-0012-5891-df1f25000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:51 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata10/archive-blob-testdata11?comp=page', '*')
  .reply(201, "", { 'content-md5': 'VJXsRKPJgaTKv8EXnmtrQg==',
  'last-modified': 'Wed, 07 Jun 2017 13:21:52 GMT',
  etag: '"0x8D4ADA82907ECEB"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '45b4bb9f-001c-0012-5891-df1f25000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:51 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=properties')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:53 GMT',
  etag: '"0x8D4ADA829ABF5D2"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-id': '2d6149b6-001c-0009-2991-df9092000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:52 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=properties')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:53 GMT',
  etag: '"0x8D4ADA829ABF5D2"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-id': '2d6149b6-001c-0009-2991-df9092000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:52 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(200, "", { 'content-length': '4194304',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:21:53 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA829ABF5D2"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P10',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '290d419b-001c-0004-3091-dfa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:53 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(200, "", { 'content-length': '4194304',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:21:53 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA829ABF5D2"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P10',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '290d419b-001c-0004-3091-dfa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:53 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:46 GMT',
  etag: '"0x8D4ADA825BAFB71"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '897ec01c-001c-0001-1791-dff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:54 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:46 GMT',
  etag: '"0x8D4ADA825BAFB71"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '897ec01c-001c-0001-1791-dff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:54 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata10?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c72d0f11-001c-000d-7c91-df2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:55 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata10?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c72d0f11-001c-000d-7c91-df2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:55 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd580ef45-001c-000f-8091-dffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:56 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd580ef45-001c-000f-8091-dffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:56 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:57 GMT',
  etag: '"0x8D4ADA82C3A6F3F"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e4e9c81b-001c-000c-1891-dfc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:57 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:57 GMT',
  etag: '"0x8D4ADA82C3A6F3F"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e4e9c81b-001c-000c-1891-dfc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:57 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:58 GMT',
  etag: '"0x8D4ADA82D1BB306"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '45b4bba2-001c-0012-5a91-df1f25000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:58 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:58 GMT',
  etag: '"0x8D4ADA82D1BB306"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '45b4bba2-001c-0012-5a91-df1f25000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:58 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:59 GMT',
  etag: '"0x8D4ADA82DAEA0C3"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'b3948abc-001c-0000-0591-df1500000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:59 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:59 GMT',
  etag: '"0x8D4ADA82DAEA0C3"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'b3948abc-001c-0000-0591-df1500000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:59 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata12/archive-blob-testdata13?comp=page', '*')
  .reply(201, "", { 'content-md5': 'VJXsRKPJgaTKv8EXnmtrQg==',
  'last-modified': 'Wed, 07 Jun 2017 13:22:03 GMT',
  etag: '"0x8D4ADA82FCB25F6"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'b77fbac5-001c-0013-5691-dff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:03 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata12/archive-blob-testdata13?comp=page', '*')
  .reply(201, "", { 'content-md5': 'VJXsRKPJgaTKv8EXnmtrQg==',
  'last-modified': 'Wed, 07 Jun 2017 13:22:03 GMT',
  etag: '"0x8D4ADA82FCB25F6"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'b77fbac5-001c-0013-5691-dff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:03 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13?comp=properties')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:04 GMT',
  etag: '"0x8D4ADA8306C9625"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-id': 'e7dceaa5-001c-000e-7491-df13e3000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:04 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13?comp=properties')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:04 GMT',
  etag: '"0x8D4ADA8306C9625"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-id': 'e7dceaa5-001c-000e-7491-df13e3000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:04 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(200, "", { 'content-length': '4194304',
  'last-modified': 'Wed, 07 Jun 2017 13:22:04 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA8306C9625"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P20',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': 'ce17cd2c-001c-0003-3991-df2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:04 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(200, "", { 'content-length': '4194304',
  'last-modified': 'Wed, 07 Jun 2017 13:22:04 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA8306C9625"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P20',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': 'ce17cd2c-001c-0003-3991-df2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:04 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:57 GMT',
  etag: '"0x8D4ADA82C3A6F3F"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '6ef28163-001c-0008-7491-df7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:05 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:21:57 GMT',
  etag: '"0x8D4ADA82C3A6F3F"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '6ef28163-001c-0008-7491-df7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:05 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata12?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c5dfe67d-001c-0005-2e91-df4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:07 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata12?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c5dfe67d-001c-0005-2e91-df4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:07 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata14?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '897ec020-001c-0001-1a91-dff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:07 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata14?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '897ec020-001c-0001-1a91-dff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:07 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:09 GMT',
  etag: '"0x8D4ADA833285816"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '25f39c6b-001c-0002-2e91-dfcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:09 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:09 GMT',
  etag: '"0x8D4ADA833285816"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '25f39c6b-001c-0002-2e91-dfcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:09 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:10 GMT',
  etag: '"0x8D4ADA833E0C143"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '26d7fdc5-001c-000a-1c91-dfa714000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:09 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:10 GMT',
  etag: '"0x8D4ADA833E0C143"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '26d7fdc5-001c-000a-1c91-dfa714000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:09 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:11 GMT',
  etag: '"0x8D4ADA83473AEFF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'e4e9c81d-001c-000c-1a91-dfc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:10 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:11 GMT',
  etag: '"0x8D4ADA83473AEFF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'e4e9c81d-001c-000c-1a91-dfc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:10 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata14/archive-blob-testdata15?comp=page', '*')
  .reply(201, "", { 'content-md5': 'VJXsRKPJgaTKv8EXnmtrQg==',
  'last-modified': 'Wed, 07 Jun 2017 13:22:14 GMT',
  etag: '"0x8D4ADA8369145E3"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'e7dceaa7-001c-000e-7691-df13e3000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:14 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata14/archive-blob-testdata15?comp=page', '*')
  .reply(201, "", { 'content-md5': 'VJXsRKPJgaTKv8EXnmtrQg==',
  'last-modified': 'Wed, 07 Jun 2017 13:22:14 GMT',
  etag: '"0x8D4ADA8369145E3"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'e7dceaa7-001c-000e-7691-df13e3000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:14 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15?comp=properties')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:16 GMT',
  etag: '"0x8D4ADA83750092D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-id': '290d41a0-001c-0004-3491-dfa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:15 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15?comp=properties')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:16 GMT',
  etag: '"0x8D4ADA83750092D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-id': '290d41a0-001c-0004-3491-dfa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:15 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata14/archive-blob-testdata15')
  .reply(200, "", { 'content-length': '4194304',
  'last-modified': 'Wed, 07 Jun 2017 13:22:16 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA83750092D"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P30',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '484a0d18-001c-000b-3a91-df4a69000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata14/archive-blob-testdata15')
  .reply(200, "", { 'content-length': '4194304',
  'last-modified': 'Wed, 07 Jun 2017 13:22:16 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA83750092D"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P30',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '484a0d18-001c-000b-3a91-df4a69000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata14?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:09 GMT',
  etag: '"0x8D4ADA833285816"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': 'c72d0f15-001c-000d-7f91-df2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:17 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata14?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:09 GMT',
  etag: '"0x8D4ADA833285816"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': 'c72d0f15-001c-000d-7f91-df2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:17 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata14?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '25f39c6e-001c-0002-3191-dfcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:18 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata14?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '25f39c6e-001c-0002-3191-dfcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:18 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata16?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7d5ceba0-001c-0006-2991-df7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:19 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata16?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7d5ceba0-001c-0006-2991-df7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:19 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata16?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:20 GMT',
  etag: '"0x8D4ADA83A32F4A9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '26d7fdc9-001c-000a-2091-dfa714000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:20 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata16?restype=container')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:20 GMT',
  etag: '"0x8D4ADA83A32F4A9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '26d7fdc9-001c-000a-2091-dfa714000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:20 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata16/archive-blob-testdata17')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:21 GMT',
  etag: '"0x8D4ADA83AC805CA"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '45b4bba7-001c-0012-5f91-df1f25000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:21 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata16/archive-blob-testdata17')
  .reply(201, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:21 GMT',
  etag: '"0x8D4ADA83AC805CA"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '45b4bba7-001c-0012-5f91-df1f25000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:21 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata16/archive-blob-testdata17copied')
  .reply(202, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:22 GMT',
  etag: '"0x8D4ADA83B613699"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-copy-status': 'success',
  'x-ms-copy-id': '0f87b273-ba54-41d9-9422-26141157e9a1',
  'x-ms-request-id': 'ce17cd30-001c-0003-3c91-df2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:21 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata16/archive-blob-testdata17copied')
  .reply(202, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:22 GMT',
  etag: '"0x8D4ADA83B613699"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-copy-status': 'success',
  'x-ms-copy-id': '0f87b273-ba54-41d9-9422-26141157e9a1',
  'x-ms-request-id': 'ce17cd30-001c-0003-3c91-df2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:21 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata16/archive-blob-testdata17copied')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:22:22 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA83B613699"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-copy-id': '0f87b273-ba54-41d9-9422-26141157e9a1',
  'x-ms-copy-progress': '0/0',
  'x-ms-copy-source': 'https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net/archive-cont-testdata16/archive-blob-testdata17',
  'x-ms-copy-status': 'success',
  'x-ms-copy-completion-time': 'Wed, 07 Jun 2017 13:22:22 GMT',
  'x-ms-access-tier': 'P20',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': 'c7451cdf-001c-0007-1091-df9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:25 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata16/archive-blob-testdata17copied')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Wed, 07 Jun 2017 13:22:22 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA83B613699"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-copy-id': '0f87b273-ba54-41d9-9422-26141157e9a1',
  'x-ms-copy-progress': '0/0',
  'x-ms-copy-source': 'https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net/archive-cont-testdata16/archive-blob-testdata17',
  'x-ms-copy-status': 'success',
  'x-ms-copy-completion-time': 'Wed, 07 Jun 2017 13:22:22 GMT',
  'x-ms-access-tier': 'P20',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': 'c7451cdf-001c-0007-1091-df9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:25 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata16?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:20 GMT',
  etag: '"0x8D4ADA83A32F4A9"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '268465ac-001c-0014-6091-df7129000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata16?restype=container')
  .reply(200, "", { 'last-modified': 'Wed, 07 Jun 2017 13:22:20 GMT',
  etag: '"0x8D4ADA83A32F4A9"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '268465ac-001c-0014-6091-df7129000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata16?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd580ef52-001c-000f-0591-dffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:28 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata16?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd580ef52-001c-000f-0591-dffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:22:28 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }]];