// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_CONNECTION_STRING'] = 'DefaultEndpointsProtocol=https;AccountName=xiaonlistage;AccountKey=null;EndpointSuffix=core.windows.net';
  process.env['AZURE_STORAGE_CONNECTION_STRING_BLOB_ACCOUNT_LRS'] = 'DefaultEndpointsProtocol=https;AccountName=xiaonlistageblob2;AccountKey=null;EndpointSuffix=core.windows.net';
  process.env['AZURE_STORAGE_CONNECTION_STRING_PREMIUM_ACCOUNT'] = 'DefaultEndpointsProtocol=https;AccountName=xiaonliprepp;AccountKey=null;EndpointSuffix=rr1xio.xstore-test.windows-int.net';
}

exports.scopes = [[function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c3625dd1-001e-0006-6e90-dfa184000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:19:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c3625dd1-001e-0006-6e90-dfa184000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:19:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata0?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:00 GMT',
  etag: '"0x8D4ADA7E6778468"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '51e98b0d-001e-0045-4390-df47d8000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:19:59 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata0?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:00 GMT',
  etag: '"0x8D4ADA7E6778468"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '51e98b0d-001e-0045-4390-df47d8000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:19:59 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata0/archive-blob-testdata1', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:02 GMT',
  etag: '"0x8D4ADA7E788022C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f5e574f8-001e-0001-1e90-dfcde7000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:20:00 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata0/archive-blob-testdata1', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:02 GMT',
  etag: '"0x8D4ADA7E788022C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f5e574f8-001e-0001-1e90-dfcde7000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:20:00 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata0/archive-blob-testdata1?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '11e1bbc0-001e-0003-1890-df735f000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:02 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata0/archive-blob-testdata1?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '11e1bbc0-001e-0003-1890-df735f000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:02 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata0/archive-blob-testdata1')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:02 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7E788022C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '019865c5-001e-001a-1590-dff3e4000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Hot',
  date: 'Wed, 07 Jun 2017 13:20:04 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata0/archive-blob-testdata1')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:02 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7E788022C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '019865c5-001e-001a-1590-dff3e4000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Hot',
  date: 'Wed, 07 Jun 2017 13:20:04 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .get('/archive-cont-testdata0?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xiaonlistageblob2.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata0\"><Blobs><Blob><Name>archive-blob-testdata1</Name><Properties><Last-Modified>Wed, 07 Jun 2017 13:20:02 GMT</Last-Modified><Etag>0x8D4ADA7E788022C</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Hot</AccessTier><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0a51412e-001e-001d-0a90-df9f87000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:05 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .get('/archive-cont-testdata0?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xiaonlistageblob2.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata0\"><Blobs><Blob><Name>archive-blob-testdata1</Name><Properties><Last-Modified>Wed, 07 Jun 2017 13:20:02 GMT</Last-Modified><Etag>0x8D4ADA7E788022C</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Hot</AccessTier><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0a51412e-001e-001d-0a90-df9f87000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:05 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:00 GMT',
  etag: '"0x8D4ADA7E6778468"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '222c9710-001e-0015-5a90-df8588000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:20:06 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:00 GMT',
  etag: '"0x8D4ADA7E6778468"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '222c9710-001e-0015-5a90-df8588000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:20:06 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata0?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f42fcb6c-001e-000d-6d90-df5aef000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:07 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata0?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f42fcb6c-001e-000d-6d90-df5aef000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:07 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '76708962-001e-0038-3690-df36fb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:08 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '76708962-001e-0038-3690-df36fb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:08 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata2?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:10 GMT',
  etag: '"0x8D4ADA7EC4F12BF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f59555ae-001e-0013-2390-dfb637000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:09 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata2?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:10 GMT',
  etag: '"0x8D4ADA7EC4F12BF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f59555ae-001e-0013-2390-dfb637000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:09 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata2/archive-blob-testdata3', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:11 GMT',
  etag: '"0x8D4ADA7ED1DB966"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fb421060-001e-0033-0790-dfcd90000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:20:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata2/archive-blob-testdata3', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:11 GMT',
  etag: '"0x8D4ADA7ED1DB966"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fb421060-001e-0033-0790-dfcd90000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:20:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '136aee36-001e-002b-1b90-df12f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '136aee36-001e-002b-1b90-df12f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:11 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7ED1DB966"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '13187a8f-001e-0042-7490-df2bbb000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Cool',
  date: 'Wed, 07 Jun 2017 13:20:13 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:11 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7ED1DB966"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '13187a8f-001e-0042-7490-df2bbb000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Cool',
  date: 'Wed, 07 Jun 2017 13:20:13 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .get('/archive-cont-testdata2?restype=container&comp=list&prefix=')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xiaonlistageblob2.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata2\"><Blobs><Blob><Name>archive-blob-testdata3</Name><Properties><Last-Modified>Wed, 07 Jun 2017 13:20:11 GMT</Last-Modified><Etag>0x8D4ADA7ED1DB966</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Cool</AccessTier><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2af6931d-001e-0012-4290-dfe9eb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .get('/archive-cont-testdata2?restype=container&comp=list&prefix=')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xiaonlistageblob2.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata2\"><Blobs><Blob><Name>archive-blob-testdata3</Name><Properties><Last-Modified>Wed, 07 Jun 2017 13:20:11 GMT</Last-Modified><Etag>0x8D4ADA7ED1DB966</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Cool</AccessTier><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2af6931d-001e-0012-4290-dfe9eb000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:10 GMT',
  etag: '"0x8D4ADA7EC4F12BF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '26fc8b47-001e-000b-1f90-df6950000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:20:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:10 GMT',
  etag: '"0x8D4ADA7EC4F12BF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '26fc8b47-001e-000b-1f90-df6950000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:20:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata2?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '985a852b-001e-0021-0b90-dfb640000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata2?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '985a852b-001e-0021-0b90-dfb640000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:16 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '87a56616-001e-0023-1f90-df08f8000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:17 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '87a56616-001e-0023-1f90-df08f8000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:17 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata4?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:19 GMT',
  etag: '"0x8D4ADA7F1B3AF64"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'dd1f9cd1-001e-0035-6590-dffe2f000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:18 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata4?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:19 GMT',
  etag: '"0x8D4ADA7F1B3AF64"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'dd1f9cd1-001e-0035-6590-dffe2f000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:18 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata4/archive-blob-testdata5', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:20 GMT',
  etag: '"0x8D4ADA7F2BA0054"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0ad0e265-001e-0028-1890-dff393000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:20:19 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata4/archive-blob-testdata5', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:20 GMT',
  etag: '"0x8D4ADA7F2BA0054"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0ad0e265-001e-0028-1890-dff393000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:20:19 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata4/archive-blob-testdata5?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '5487657f-001e-003f-0790-df5a98000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata4/archive-blob-testdata5?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '5487657f-001e-003f-0790-df5a98000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata4/archive-blob-testdata5')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:20 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7F2BA0054"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '80173ec4-001e-0037-7f90-df4097000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  date: 'Wed, 07 Jun 2017 13:20:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata4/archive-blob-testdata5')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:20 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7F2BA0054"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '80173ec4-001e-0037-7f90-df4097000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  date: 'Wed, 07 Jun 2017 13:20:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .get('/archive-cont-testdata4?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xiaonlistageblob2.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata4\"><Blobs><Blob><Name>archive-blob-testdata5</Name><Properties><Last-Modified>Wed, 07 Jun 2017 13:20:20 GMT</Last-Modified><Etag>0x8D4ADA7F2BA0054</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Archive</AccessTier><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '831720f7-001e-003a-6290-df8843000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .get('/archive-cont-testdata4?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xiaonlistageblob2.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata4\"><Blobs><Blob><Name>archive-blob-testdata5</Name><Properties><Last-Modified>Wed, 07 Jun 2017 13:20:20 GMT</Last-Modified><Etag>0x8D4ADA7F2BA0054</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Archive</AccessTier><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '831720f7-001e-003a-6290-df8843000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:19 GMT',
  etag: '"0x8D4ADA7F1B3AF64"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9f7a6c5c-001e-0046-0d90-dfa6bc000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:20:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:19 GMT',
  etag: '"0x8D4ADA7F1B3AF64"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9f7a6c5c-001e-0046-0d90-dfa6bc000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:20:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata4?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd2664832-001e-0020-0190-dfe99c000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata4?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd2664832-001e-0020-0190-dfe99c000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:26 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2f6d546f-001e-0014-5f90-dfda54000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2f6d546f-001e-0014-5f90-dfda54000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata6?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:26 GMT',
  etag: '"0x8D4ADA7F5ECB7C9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '313ea878-001e-0039-6290-df6927000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata6?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:26 GMT',
  etag: '"0x8D4ADA7F5ECB7C9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '313ea878-001e-0039-6290-df6927000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata6/archive-blob-testdata7', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:30 GMT',
  etag: '"0x8D4ADA7F8472BBF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7ea35b3f-001e-002a-0390-df4d2b000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:20:29 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata6/archive-blob-testdata7', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:30 GMT',
  etag: '"0x8D4ADA7F8472BBF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7ea35b3f-001e-002a-0390-df4d2b000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:20:29 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '91582cc1-001e-0005-0190-df40e0000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '91582cc1-001e-0005-0190-df40e0000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata6/archive-blob-testdata7')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:30 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7F8472BBF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3d4c385a-001e-001b-6890-dfac38000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  date: 'Wed, 07 Jun 2017 13:20:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata6/archive-blob-testdata7')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:30 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7F8472BBF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3d4c385a-001e-001b-6890-dfac38000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  date: 'Wed, 07 Jun 2017 13:20:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7?comp=tier')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4372e2e0-001e-003c-7990-dfbbfc000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:32 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7?comp=tier')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4372e2e0-001e-003c-7990-dfbbfc000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:32 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata6/archive-blob-testdata7')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:30 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7F8472BBF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '47d07ddc-001e-0018-4390-df4d5c000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  'x-ms-archive-status': 'rehydrate-pending-to-hot',
  date: 'Wed, 07 Jun 2017 13:20:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata6/archive-blob-testdata7')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:30 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7F8472BBF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '47d07ddc-001e-0018-4390-df4d5c000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  'x-ms-archive-status': 'rehydrate-pending-to-hot',
  date: 'Wed, 07 Jun 2017 13:20:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .get('/archive-cont-testdata6?restype=container&comp=list&prefix=')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xiaonlistageblob2.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata6\"><Blobs><Blob><Name>archive-blob-testdata7</Name><Properties><Last-Modified>Wed, 07 Jun 2017 13:20:30 GMT</Last-Modified><Etag>0x8D4ADA7F8472BBF</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Archive</AccessTier><ArchiveStatus>rehydrate-pending-to-hot</ArchiveStatus><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '92b9cbcd-001e-0025-3e90-df3b47000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:35 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .get('/archive-cont-testdata6?restype=container&comp=list&prefix=')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xiaonlistageblob2.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata6\"><Blobs><Blob><Name>archive-blob-testdata7</Name><Properties><Last-Modified>Wed, 07 Jun 2017 13:20:30 GMT</Last-Modified><Etag>0x8D4ADA7F8472BBF</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Archive</AccessTier><ArchiveStatus>rehydrate-pending-to-hot</ArchiveStatus><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '92b9cbcd-001e-0025-3e90-df3b47000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:35 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:26 GMT',
  etag: '"0x8D4ADA7F5ECB7C9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '334858f4-001e-0000-1a90-df923b000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:20:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:26 GMT',
  etag: '"0x8D4ADA7F5ECB7C9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '334858f4-001e-0000-1a90-df923b000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:20:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata6?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3c91db62-001e-002f-5090-df9ff0000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata6?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3c91db62-001e-002f-5090-df9ff0000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:36 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b8bfc832-001e-000a-5590-df368c000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:37 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b8bfc832-001e-000a-5590-df368c000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:37 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata8?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:40 GMT',
  etag: '"0x8D4ADA7FE5F13CD"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '55627570-001e-0043-5690-df7467000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata8?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:40 GMT',
  etag: '"0x8D4ADA7FE5F13CD"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '55627570-001e-0043-5690-df7467000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata8/archive-blob-testdata9', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:41 GMT',
  etag: '"0x8D4ADA7FF37230D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a22addff-001e-0031-2f90-df7328000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:20:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata8/archive-blob-testdata9', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:41 GMT',
  etag: '"0x8D4ADA7FF37230D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a22addff-001e-0031-2f90-df7328000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:20:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ed1e3bde-001e-003e-1690-df0544000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ed1e3bde-001e-003e-1690-df0544000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata8/archive-blob-testdata9')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:41 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7FF37230D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e1fa41a1-001e-0036-4490-df1f4b000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  date: 'Wed, 07 Jun 2017 13:20:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata8/archive-blob-testdata9')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:41 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7FF37230D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e1fa41a1-001e-0036-4490-df1f4b000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  date: 'Wed, 07 Jun 2017 13:20:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9?comp=tier')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f5e58020-001e-0001-0690-dfcde7000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9?comp=tier')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f5e58020-001e-0001-0690-dfcde7000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata8/archive-blob-testdata9')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:41 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7FF37230D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '11e1c94c-001e-0003-4190-df735f000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  'x-ms-archive-status': 'rehydrate-pending-to-cool',
  date: 'Wed, 07 Jun 2017 13:20:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata8/archive-blob-testdata9')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:41 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA7FF37230D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '11e1c94c-001e-0003-4190-df735f000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  'x-ms-archive-status': 'rehydrate-pending-to-cool',
  date: 'Wed, 07 Jun 2017 13:20:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .get('/archive-cont-testdata8?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xiaonlistageblob2.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata8\"><Blobs><Blob><Name>archive-blob-testdata9</Name><Properties><Last-Modified>Wed, 07 Jun 2017 13:20:41 GMT</Last-Modified><Etag>0x8D4ADA7FF37230D</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Archive</AccessTier><ArchiveStatus>rehydrate-pending-to-cool</ArchiveStatus><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '01987260-001e-001a-1690-dff3e4000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .get('/archive-cont-testdata8?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xiaonlistageblob2.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata8\"><Blobs><Blob><Name>archive-blob-testdata9</Name><Properties><Last-Modified>Wed, 07 Jun 2017 13:20:41 GMT</Last-Modified><Etag>0x8D4ADA7FF37230D</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Archive</AccessTier><ArchiveStatus>rehydrate-pending-to-cool</ArchiveStatus><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '01987260-001e-001a-1690-dff3e4000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:40 GMT',
  etag: '"0x8D4ADA7FE5F13CD"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '222ca4dd-001e-0015-5190-df8588000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:20:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:40 GMT',
  etag: '"0x8D4ADA7FE5F13CD"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '222ca4dd-001e-0015-5190-df8588000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:20:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata8?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f5955bc1-001e-0013-1c90-dfb637000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata8?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f5955bc1-001e-0013-1c90-dfb637000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:49 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b132fa43-001e-0047-6690-dff960000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b132fa43-001e-0047-6690-dff960000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata10?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:52 GMT',
  etag: '"0x8D4ADA8058145FE"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '373d6d63-001e-0049-6d90-dfd0d0000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata10?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:52 GMT',
  etag: '"0x8D4ADA8058145FE"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '373d6d63-001e-0049-6d90-dfd0d0000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata10/archive-blob-testdata11', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:53 GMT',
  etag: '"0x8D4ADA80622D488"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ae513518-001e-0024-0b90-df649b000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:20:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata10/archive-blob-testdata11', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:53 GMT',
  etag: '"0x8D4ADA80622D488"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ae513518-001e-0024-0b90-df649b000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:20:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f6d44111-001e-0008-2490-df8834000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:54 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f6d44111-001e-0008-2490-df8834000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:54 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:53 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA80622D488"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '131884e1-001e-0042-5590-df2bbb000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  date: 'Wed, 07 Jun 2017 13:20:55 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:53 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA80622D488"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '131884e1-001e-0042-5590-df2bbb000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  date: 'Wed, 07 Jun 2017 13:20:55 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=tier')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '26fc9e17-001e-000b-3e90-df6950000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:55 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=tier')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '26fc9e17-001e-000b-3e90-df6950000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:55 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:53 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA80622D488"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '985a989d-001e-0021-6690-dfb640000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  'x-ms-archive-status': 'rehydrate-pending-to-hot',
  date: 'Wed, 07 Jun 2017 13:20:56 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:20:53 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4ADA80622D488"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '985a989d-001e-0021-6690-dfb640000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  'x-ms-access-tier': 'Archive',
  'x-ms-archive-status': 'rehydrate-pending-to-hot',
  date: 'Wed, 07 Jun 2017 13:20:56 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=tier')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>BlobBeingRehydrated</Code><Message>This operation is not permitted because the blob is being rehydrated.\nRequestId:87a5781d-001e-0023-2190-df08f8000000\nTime:2017-06-07T13:20:59.0637091Z</Message></Error>", { 'content-length': '257',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '87a5781d-001e-0023-2190-df08f8000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=tier')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>BlobBeingRehydrated</Code><Message>This operation is not permitted because the blob is being rehydrated.\nRequestId:87a5781d-001e-0023-2190-df08f8000000\nTime:2017-06-07T13:20:59.0637091Z</Message></Error>", { 'content-length': '257',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '87a5781d-001e-0023-2190-df08f8000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:20:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:52 GMT',
  etag: '"0x8D4ADA8058145FE"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e28aebf7-001e-0026-7590-dfda23000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:20:59 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:20:52 GMT',
  etag: '"0x8D4ADA8058145FE"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e28aebf7-001e-0026-7590-dfda23000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:20:59 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata10?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6c2aa64f-001e-001c-6b90-dfc05b000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:00 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata10?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6c2aa64f-001e-001c-6b90-dfc05b000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:00 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0ad0ea7a-001e-0028-1f90-dff393000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:02 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0ad0ea7a-001e-0028-1f90-dff393000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:02 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata12?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:21:03 GMT',
  etag: '"0x8D4ADA80C243313"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '54877380-001e-003f-0290-df5a98000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata12?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:21:03 GMT',
  etag: '"0x8D4ADA80C243313"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '54877380-001e-003f-0290-df5a98000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata12/archive-blob-testdata13', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:21:05 GMT',
  etag: '"0x8D4ADA80D14A098"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3b6c5921-001e-0032-5f90-df924c000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:21:04 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata12/archive-blob-testdata13', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Wed, 07 Jun 2017 13:21:05 GMT',
  etag: '"0x8D4ADA80D14A098"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3b6c5921-001e-0032-5f90-df924c000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 07 Jun 2017 13:21:04 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13?comp=tier')
  .reply(400, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.\nRequestId:1227fb27-001e-0017-6f90-df3b30000000\nTime:2017-06-07T13:21:06.0347735Z</Message><HeaderName>x-ms-access-tier</HeaderName><HeaderValue>P10</HeaderValue></Error>", { 'content-length': '325',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1227fb27-001e-0017-6f90-df3b30000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:05 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13?comp=tier')
  .reply(400, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.\nRequestId:1227fb27-001e-0017-6f90-df3b30000000\nTime:2017-06-07T13:21:06.0347735Z</Message><HeaderName>x-ms-access-tier</HeaderName><HeaderValue>P10</HeaderValue></Error>", { 'content-length': '325',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1227fb27-001e-0017-6f90-df3b30000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:05 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:21:03 GMT',
  etag: '"0x8D4ADA80C243313"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9f7a762e-001e-0046-6f90-dfa6bc000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:21:06 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Jun 2017 13:21:03 GMT',
  etag: '"0x8D4ADA80C243313"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9f7a762e-001e-0046-6f90-dfa6bc000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Wed, 07 Jun 2017 13:21:06 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata12?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ac7dcb08-001e-0044-1a90-df1804000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:08 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonlistageblob2.blob.core.windows.net:443')
  .delete('/archive-cont-testdata12?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ac7dcb08-001e-0044-1a90-df1804000000',
  'x-ms-version': '2017-04-17',
  date: 'Wed, 07 Jun 2017 13:21:08 GMT',
  connection: 'close' });
 return result; }]];